DROP TABLE IF EXISTS tabla1;
CREATE TABLE tabla1 (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "dni" INTEGER PRIMARY KEY NOT NULL,
    "nombre" TEXT,
    "apellido" TEXT,
    "cantidad" INTEGER,
    "monto" DOUBLE PRECISION
);

-- Crear la funcion para actualizar updated_at
CREATE OR REPLACE FUNCTION update_tabla1_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Crear el trigger que llama a la funcion antes de actualizar
CREATE TRIGGER update_tabla1_updated_at_trigger
BEFORE UPDATE ON tabla1
FOR EACH ROW
EXECUTE FUNCTION update_tabla1_updated_at();

-- Crear indice unico
CREATE UNIQUE INDEX unique_tabla1_nombre_apellido
ON tabla1 ("nombre", "apellido");
