DROP TABLE IF EXISTS servicios;
CREATE TABLE servicios (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "Ruta Servicio" TEXT,
    "Servicio" TEXT,
    "Entidad" TEXT,
    "codigo" INTEGER,
    "Nombre Carpeta" TEXT,
    "Codificacion" TEXT PRIMARY KEY NOT NULL,
    "Fecha Creacion" timestamp without time zone,
    "Guiones" TEXT,
    "Empieza con S" TEXT,
    "Sin 0 Izquierda" TEXT,
    "Es Numero" TEXT,
    "Codigo Duplicado" TEXT,
    "Errores" INTEGER
);

-- Crear la funcion para actualizar updated_at
CREATE OR REPLACE FUNCTION update_servicios_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Crear el trigger que llama a la funcion antes de actualizar
CREATE TRIGGER update_servicios_updated_at_trigger
BEFORE UPDATE ON servicios
FOR EACH ROW
EXECUTE FUNCTION update_servicios_updated_at();

-- Crear indice unico
CREATE UNIQUE INDEX unique_servicios_servicio_entidad_codigo
ON servicios ("Servicio", "Entidad", "codigo");
